version: 2
analyze.output.format: pdf
selenium:
  driver: "chrome"
  driverOptions:
    - "--start-maximized"
    - "--disable-headless" 
    - "--no-sandbox"
    - "--disable-dev-shm-usage"
  visible: true
  executablePath: ".\\node_modules\\chromedriver\\bin\\chromedriver"
  logPath: ".\\selenium.log"