version: 2

analyze.output.format: pdf

selenium:

  driver: "chrome"

  driverOptions:

    - "--start-maximized"

    - "--disable-headless"

    - "--no-sandbox"

    - "--disable-dev-shm-usage"

    - "--remote-allow-origins=*"

  visible: true

  remoteUrl: "http://localhost:4444/wd/hub"  # Add this line