version: 2

analyze.output.format: pdf

selenium:
  driver: "chrome"
  driverOptions:
    - "--start-maximized"
  executablePath: "2025-MBT-F\\node_modules\\chromedriver\\bin\\chromedriver"
  logPath: "C:\\Users\\User\\Desktop\\selenium.log"